INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: Cannot convert beta to a tensor variable.
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: Cannot convert beta to a tensor variable.
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: Cannot convert beta to a tensor variable.
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: Cannot convert beta to a tensor variable.
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
INFO:C:\Users\saide\anaconda3\envs\pymc_env\Lib\site-packages\pytensor\link\c\lazylinker_c.py:Compiling new CVM
INFO:C:\Users\saide\anaconda3\envs\pymc_env\Lib\site-packages\pytensor\link\c\lazylinker_c.py:New version 0.212
INFO:pymc.sampling.mcmc:Auto-assigning NUTS sampler...
INFO:pymc.sampling.mcmc:Initializing NUTS using jitter+adapt_diag...
ERROR:root:An error occurred: Initial evaluation of model at starting point failed!
Starting values:
{'mu_alpha': array(-0.54376195), 'sigma_alpha_log__': array(-0.39411324), 'mu_beta': array(-0.59913227), 'sigma_beta_log__': array(0.94219354), 'alpha': array([-0.24250739, -0.41350621, -0.07916025, -1.08011046, -0.32343027]), 'beta': array([-0.23444364, -0.53336823, -0.2940355 , -1.30219624, -0.89597474,
       -0.84699292,  0.19286456, -0.99349488]), 'sigma_log__': array(-0.19796335)}

Logp initial evaluation results:
{'mu_alpha': -1.07, 'sigma_alpha': -1.22, 'mu_beta': -1.1, 'sigma_beta': -1.54, 'alpha': -3.35, 'beta': -15.01, 'sigma': -1.16, 'y_obs': nan}
You can call `model.debug()` for more details.
# updated demo_model
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: This function requires the python library graphviz, along with binaries. The easiest way to install all of this is by running

	conda install -c conda-forge python-graphviz
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: failed to execute ['dot.bat', '-Tpng', '-O', 'model_debug'], make sure the Graphviz executables are on your systems' PATH
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: failed to execute ['dot.bat', '-Tpng', '-O', 'model_debug'], make sure the Graphviz executables are on your systems' PATH
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
ERROR:root:An error occurred: failed to execute ['dot.bat', '-Tpng', '-O', 'model_debug'], make sure the Graphviz executables are on your systems' PATH
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
INFO:pymc.sampling.mcmc:Auto-assigning NUTS sampler...
INFO:pymc.sampling.mcmc:Initializing NUTS using adapt_diag...
INFO:pymc.sampling.mcmc:Multiprocess sampling (4 chains in 4 jobs)
INFO:pymc.sampling.mcmc:NUTS: [mu_alpha, sigma_alpha, mu_beta, sigma_beta, alpha, beta, sigma]
INFO:pymc.sampling.mcmc:Sampling 4 chains for 200 tune and 500 draw iterations (800 + 2_000 draws total) took 1335 seconds.
INFO:pymc.stats.convergence:The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
ERROR:pymc.stats.convergence:The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
WARNING:pymc.stats.convergence:Chain 0 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 1 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 2 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 3 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
ERROR:root:An error occurred: log likelihood not found in inference data object
INFO:root:Loading data...
ERROR:root:An error occurred: [Errno 2] No such file or directory: 'etf_data/preprocessed_data.csv'
INFO:root:Loading data...
INFO:root:Preparing data...
INFO:root:Building hierarchical model...
INFO:pymc.sampling.mcmc:Auto-assigning NUTS sampler...
INFO:pymc.sampling.mcmc:Initializing NUTS using adapt_diag...
INFO:pymc.sampling.mcmc:Multiprocess sampling (4 chains in 4 jobs)
INFO:pymc.sampling.mcmc:NUTS: [mu_alpha, sigma_alpha, mu_beta, sigma_beta, alpha, beta, sigma]
INFO:pymc.sampling.mcmc:Sampling 4 chains for 200 tune and 500 draw iterations (800 + 2_000 draws total) took 940 seconds.
INFO:pymc.stats.convergence:The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
ERROR:pymc.stats.convergence:The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
WARNING:pymc.stats.convergence:Chain 0 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 1 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 2 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
WARNING:pymc.stats.convergence:Chain 3 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
INFO:root:Plotting trace plots...
ERROR:root:An error occurred: log likelihood not found in inference data object
ERROR:ipykernel.comm:No such comm target registered: jupyter.widget.control
WARNING:Comm:No such comm: 77078bc6-68e4-49b5-8207-ab7d4e939b22
